language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo add-apt-repository ppa:pylab/stable -y  # For SciPY
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-scipy
install: "./update.sh"
before_script: "paster serve development-france.ini &"
script: "test/integration/formula.sh"
